# Generated by Django 3.0.8 on 2020-08-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared_mode',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
