# Generated by Django 3.0.8 on 2020-08-23 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kudos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='marked_user',
            field=models.ManyToManyField(blank=True, related_name='marking_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='mention_user',
            field=models.ManyToManyField(blank=True, related_name='mentioned_by_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
