# Generated by Django 3.0.8 on 2020-08-26 10:07

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_auto_20200823_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='marked_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='marking_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='mention_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='mentioned_by_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
