# Generated by Django 3.0.8 on 2020-08-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200827_1142'),
        ('post', '0003_auto_20200826_1007'),
    ]

    operations = [
    ]
