# Generated by Django 3.0.8 on 2020-08-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_merge_20200827_2030'),
        ('post', '0002_post_shared_mode'),
    ]

    operations = [
    ]
