# Generated by Django 3.0.7 on 2020-08-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_merge_20200827_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='C:\\Users\\lenovo\\Desktop\\GoogleSPS\\Graminsta\\backend\\graminsta\\media'),
        ),
    ]
